name: "CI: Validate & Test"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          # You will need to paste your specific provider string here
          workload_identity_provider: 'projects/115741126538/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'pipeline-sa@cat-risk-pipeline-2026.iam.gserviceaccount.com'

      - name: Install Dependencies
        run: |
          pip install flake8 pytest apache-beam[gcp] requests google-cloud-pubsub

      # - name: Lint Code
      #   run: flake8 . --count --max-line-length=100 --statistics
      - name: Lint with flake8
        run: |
          # Only FAIL if there are syntax errors or "scary" logic issues
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          
          # Report everything else (line length, spacing) but don't stop the build
          # --exit-zero means "always succeed"
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

      - name: Run Tests
        run: pytest cat-risk-pipeline/tests/ -v --import-mode=importlib

      - name: Terraform Validate
        run: |
          cd terraform
          terraform init -backend=false
          terraform validate